---
services:
  broker:
    image: eclipse-mosquitto:2.1.2-alpine@sha256:6f8d8a947c506f8a2290ec65cd4bd2bc7cb4d43fb5f6271f861cb013e2ef9797
    container_name: mosquitto-tls
    hostname: mosquitto-tls
    volumes:
      - /docker/data/mosquitto:/mosquitto/data
      #FIXME PWD is not compatible with Git Worktrees when updating the docker containers
      - "${PWD}/config:/mosquitto/config" #FIXME "PWD" might not work in all environments
      - "${PWD}/certs:/mosquitto/certs" #FIXME "PWD" might not work in all environments
    network_mode: bridge
    ports:
      - "7006:7006"
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf
...
