---
volumes:
  backup:
    name: backup/prowlarr
    driver: zfs
    driver_opts:
      - checksum=sha512
      - dedup=verify
  config:
    name: config/prowlarr
    driver: zfs

services:
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:1.25.4@sha256:1e2fffd859ecd260e4aae4798cf5be75938cd602161d21b1d58122afb397c864
    container_name: prowlarr
    hostname: prowlarr
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Berlin
      - UMASK_SET=022
    volumes:
      - backup:/backups
      - config:/config
    network_mode: bridge
    ports:
      - "9696:9696"
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf
