---
services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.5.2@sha256:c80ae007ce2ccdcd217a12426e4f039ef763ff90738c808d38810c3e59323767
    container_name: flaresolverr
    hostname: flaresolverr
    environment:
#      - LOG_LEVEL=info
#      - LOG_HTML=false
#      - CAPTCHA_SOLVER=none
      - TZ=Europe/Berlin
#      - LANG=en_US
    network_mode: bridge
    ports:
      - "8191:8191"
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf
