---
services:
  isponsorblocktv:
    image: ghcr.io/dmunozv04/isponsorblocktv:v2.11.0@sha256:d1e876636754fb2b54490feebe3af4a321f7f2a932a2d57b67b2a667eea40823
    container_name: isponsorblocktv
    hostname: isponsorblocktv
    volumes:
      - /docker/data/isponsorblocktv:/app/data
    network_mode: host
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf
...
