---
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.11.4@sha256:9591b13f13843c7721c2b8eaf7382846c81b3ffe126526d1888d1fed50c6a33f
    container_name: open-webui
    hostname: open-webui
    env_file:
      - open-webui.env
    volumes:
      - "/docker/data/open-webui:/app/backend/data"
      - "/docker/cache/open-webui:/app/backend/data/cache"
    network_mode: bridge
    ports:
      - "3059:8080"
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf

volumes:
  open-webui:
    external: true
