---
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.8.8@sha256:b478adc66210c1effe147d3e4a0d8845c0418b136ca14c314b9d83a087ad1c1f
    container_name: open-webui
    hostname: open-webui
    env_file:
      - open-webui.env
    volumes:
      - "/docker/data/open-webui:/app/backend/data"
      - "/docker/cache/open-webui:/app/backend/data/cache"
    network_mode: bridge
    ports:
      - "3059:8080"
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf

volumes:
  open-webui:
    external: true
