---
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.11.3@sha256:41daa0cf2561a5d4c8d1ff31ee2a98d93ab4d3ac2605cac69366ff6a3374a933
    container_name: open-webui
    hostname: open-webui
    env_file:
      - open-webui.env
    volumes:
      - "/docker/data/open-webui:/app/backend/data"
      - "/docker/cache/open-webui:/app/backend/data/cache"
    network_mode: bridge
    ports:
      - "3059:8080"
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf

volumes:
  open-webui:
    external: true
