---
services:
  web:
    image: ghcr.io/analogj/scrutiny:v0.9.2-web@sha256:71be54e9960826f356fe290eb196762b2e18001e39f6ee09eeb17fe926acbf2c
    container_name: scrutiny-web
    hostname: scrutiny-web
    env_file:
      - scrutiny-web.env
    volumes:
      - /docker/config/scrutiny/web:/opt/scrutiny/config
    network_mode: bridge
    ports:
      - "8076:8080"
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf
