---
services:
  web:
    image: ghcr.io/analogj/scrutiny:v0.9.5-web@sha256:4f2ec0c874aec7fb0da5505b8ee127a8d7ac5b9d2b0622b53cf27fb47693877c
    container_name: scrutiny-web
    hostname: scrutiny-web
    env_file:
      - scrutiny-web.env
    volumes:
      - /docker/config/scrutiny/web:/opt/scrutiny/config
    network_mode: bridge
    ports:
      - "8076:8080"
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf
