---
services:
  web:
    image: ghcr.io/analogj/scrutiny:v0.9.4-web@sha256:a566f3c2e804d2534fa8cb75f813c75a4a356a57186239ecf96eab851517ab77
    container_name: scrutiny-web
    hostname: scrutiny-web
    env_file:
      - scrutiny-web.env
    volumes:
      - /docker/config/scrutiny/web:/opt/scrutiny/config
    network_mode: bridge
    ports:
      - "8076:8080"
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf
