# Listener on port 7006 for TLS
listener 7006

# Path to certs and key
certfile /mosquitto/certs/fullchain.pem
keyfile /mosquitto/certs/privkey.pem
cafile /mosquitto/certs/root.pem

# Allow anonymous connections
allow_anonymous true
