---
services:
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.20.14@sha256:b89f83345532cfba72690185257eb6c4f92fc2a782332a42abe19c07b7a6595f
    container_name: paperless-ngx
    hostname: paperless-ngx
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    env_file: paperless-ngx.env
    volumes:
      - /docker/data/paperless-ngx/data:/usr/src/paperless/data
      - /docker/data/paperless-ngx/media:/usr/src/paperless/media
      - /docker/data/paperless-ngx/export:/usr/src/paperless/export
      - /docker/cache/paperless-ngx/consume:/usr/src/paperless/consume
      - consume-tn-main-1:/usr/src/paperless/consume/tn-main-1
      #FIXME PWD is not compatible with Git Worktrees when updating the docker containers
      - "${PWD}/scripts:/scripts:ro" #FIXME "PWD" might not work in all environments
    labels:
      - "de.panzer1119.docker.volume.default.cifs.host=op://Docker/Paperless/CIFS/Host"
      - "de.panzer1119.docker.volume.default.cifs.username=op://Docker/Paperless/CIFS/Username"
      - "de.panzer1119.docker.volume.default.cifs.password=op://Docker/Paperless/CIFS/Password"
      - "de.panzer1119.docker.volume.paperless-ngx_consume_tn-main-1.cifs.share=op://Docker/Paperless/CIFS/Share_Consume"
    ports:
      - "8217:8000"
    healthcheck:
      test: [ "CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf

  db:
    image: postgres:16@sha256:5a65324fe84dc41709ff914e90b07f3e2f577073ed27bf917d4873aca0c9ec51
    env_file: db.env
    volumes:
      - /docker/data/paperless-ngx/postgres:/var/lib/postgresql/data
    networks:
      - default
      - backup-net
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf

  broker:
    image: redis:7@sha256:24ea35ee039d7345bef2377611e3b1a615231746de4cfea74c1414575ee56167
    volumes:
      - /docker/cache/paperless-ngx/broker:/data
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf

  gotenberg:
    image: gotenberg/gotenberg:8.31@sha256:f0d86e8a1dbc7b33a5a65cb251d02bb271a48ffa989da3feb5ed7d954fe4d4b3
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf

  tika:
    image: apache/tika:3.3.0.0@sha256:2a565f1ea1290bdcb74a7d35957d16a989ed44ef98790dcdcc28121d728fa583
#    image: apache/tika:2.9.2.1-full
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf

  paperless-ai:
    image: clusterzx/paperless-ai:3.0.9@sha256:2b65888163fd59716f1c8285b31c5bd0b30c9c3c192c42b516688e3887d4ba60
    container_name: paperless-ai
    hostname: paperless-ai
    depends_on:
      - webserver
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges=true
    env_file:
      - paperless-ai.env
    volumes:
      - /docker/data/paperless-ngx/paperless-ai:/app/data
    ports:
      - "3467:3000"
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf

volumes:
  consume-tn-main-1:
    name: paperless-ngx_consume_tn-main-1
    # Because this is a cifs volume, and it needs credentials, it is created outside of this file
    external: true

networks:
  backup-net:
    name: backup-net
    external: true
...
