---
name: apprise

services:
  apprise:
    image: caronc/apprise:1.5@sha256:c5ea17408c10fd84c8fdb05a421114a1a677b16343c274bf9b1a55701b530829
    container_name: apprise
    hostname: apprise
    environment:
      - TZ=Europe/Berlin
      - PGID=1000
      - PUID=1000
      - APPRISE_DEFAULT_THEME=dark
      - APPRISE_STATEFUL_MODE=simple
      - APPRISE_CONFIG_LOCK=yes
      - APPRISE_WORKER_COUNT=4
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - /docker/config/apprise:/config
      - "${PWD}/config/pushover.yml:/config/pushover.yml:ro"
    ports:
      - "8116:8000"
    network_mode: bridge
    restart: always
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf
