---
services:
  router:
    image: ghcr.io/itzg/mc-router:1.44.0
    container_name: mc-router
    hostname: mc-router
    depends_on:
      - server_atm10
    environment:
      TZ: "Europe/Berlin"
      IN_DOCKER: "true"
      METRICS_BACKEND: "prometheus"
      #TODO How do I access the prometheus metrics from outside the container?
      RECORD_LOGINS: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "25565:25565"
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf

  server_atm10:
    image: ghcr.io/itzg/minecraft-server:stable-java25-jdk
    tty: true
    stdin_open: true
    container_name: mc-server-atm10
    hostname: mc-server-atm10
    env_file:
      - defaults/server.env
      - atm10/server.env
    volumes:
      - "./defaults:/defaults:ro"
      - "./downloads:/downloads:ro"
      - "./atm10/config:/config:ro"
      - "/docker/data/minecraft/server/atm10:/data"
      - "/docker/data/minecraft/backup/simplebackups/atm10:/simplebackups"
    labels:
      - "mc-router.host=op://Docker/Minecraft/ATM10/MC-Router-Host"
    healthcheck:
      test: mc-health
      start_period: 10m
      interval: 5s
      retries: 20
    stop_grace_period: 1m
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf

  web_atm10:
    # There is no newer version of itzg/rcon available, so we use the latest tag for now
    image: itzg/rcon:latest
    container_name: mc-web-atm10
    hostname: mc-web-atm10
    depends_on:
      - server_atm10
    env_file:
      - defaults/web.env
      - atm10/web.env
    ports:
      - "4326:4326"
      - "4327:4327"
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf

  backup_borg_atm10:
    image: ghcr.io/panzer1119/mc-backup:2026.7.16
    container_name: mc-backup-borg-atm10
    hostname: mc-backup-borg-atm10
    depends_on:
      server_atm10:
        condition: service_healthy
    env_file:
      - defaults/backup_borg.env
      - atm10/backup_borg.env
    #command: now
    #entrypoint: bash
    volumes:
      - "/docker/data/minecraft/server/atm10:/data:ro"
      - "/docker/data/minecraft/backup/borg/atm10:/borg"
      - "/docker/cache/minecraft/backup/borg/atm10:/base"
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf

#  server_atm9_pcfreak9000:
#    image: ghcr.io/itzg/minecraft-server:stable-java25-jdk
#    tty: true
#    stdin_open: true
#    container_name: mc-server-atm9-pcfreak9000
#    hostname: mc-server-atm9-pcfreak9000
#    env_file:
#      - defaults/server.env
#      - atm9_pcfreak9000/server.env
#    volumes:
#      - "./defaults:/defaults:ro"
#      - "./downloads:/downloads:ro"
#      - "/docker/data/minecraft/server/atm9_pcfreak9000:/data"
#    labels:
#      - "mc-router.host=op://Docker/Minecraft/ATM9-pcfreak9000/MC-Router-Host"
#    healthcheck:
#      test: mc-health
#      start_period: 10m
#      interval: 5s
#      retries: 20
#    stop_grace_period: 1m
#    restart: unless-stopped
#    extends:
#      file: ../../common/docker-compose.yml
#      service: logging-gelf
#
#  backup_borg_atm9_pcfreak9000:
#    image: ghcr.io/panzer1119/mc-backup:2026.7.16
#    container_name: mc-backup-borg-atm9-pcfreak9000
#    hostname: mc-backup-borg-atm9-pcfreak9000
#    depends_on:
#      server_atm9_pcfreak9000:
#        condition: service_healthy
#    env_file:
#      - defaults/backup_borg.env
#      - atm9_pcfreak9000/backup_borg.env
#    #command: now
#    #entrypoint: bash
#    volumes:
#      - "/docker/data/minecraft/server/atm9_pcfreak9000:/data:ro"
#      - "/docker/data/minecraft/backup/borg/atm9_pcfreak9000:/borg"
#      - "/docker/cache/minecraft/backup/borg/atm9_pcfreak9000:/base"
#    restart: unless-stopped
#    extends:
#      file: ../../common/docker-compose.yml
#      service: logging-gelf
...
