---
services:
  speedtest-tracker:
    image: ghcr.io/linuxserver/speedtest-tracker:version-v1.14.3@sha256:79c00631575dec6d91c10ed904c211224f00813013a305c2284324e195a538bb
    container_name: speedtest-tracker
    hostname: speedtest-tracker
    depends_on:
      - db
      - cache
    env_file:
      - speedtest-tracker.env
    volumes:
      - /docker/config/speedtest-tracker:/config
    ports:
      - "8765:80"
    healthcheck:
      test: curl -fSs http://localhost:80/api/healthcheck || exit 1
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 10s
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf

  cache:
    image: redis:7.4-alpine@sha256:6ab0b6e7381779332f97b8ca76193e45b0756f38d4c0dcda72dbb3c32061ab99
    command: redis-server --save 20 1 --loglevel warning --requirepass $${REDIS_PASSWORD}
    env_file:
      - cache.env
    volumes:
      - /docker/cache/speedtest-tracker/redis:/data
    #    expose:
    #      - '6379'
    #    ports:
    #      - '6379:6379'
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf

  db:
    image: postgres:15@sha256:1b92e7a80c021647bf70f5d3eb66066a998e4f5cf43c07bb9dc9f729782cf88e
    env_file:
      - db.env
    volumes:
      - /docker/data/speedtest-tracker/postgres:/var/lib/postgresql/data
    networks:
      - default
      - backup-net
    #    ports:
    #      - "5434:5432"
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf

networks:
  backup-net:
    name: backup-net
    external: true
...
