---
services:
  speedtest-tracker:
    image: ghcr.io/linuxserver/speedtest-tracker:version-v1.15.0@sha256:3f8a2d06703bde3a6d04dcc8178fcd6251b601ce3b8b52958779d5335b5719d1
    container_name: speedtest-tracker
    hostname: speedtest-tracker
    depends_on:
      - db
      - cache
    env_file:
      - speedtest-tracker.env
    volumes:
      - /docker/config/speedtest-tracker:/config
    ports:
      - "8765:80"
    healthcheck:
      test: curl -fSs http://localhost:80/api/healthcheck || exit 1
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 10s
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf

  cache:
    image: redis:7.4-alpine@sha256:858f009f9709ce576febc734aa78b8f6d624b82571f9ddb6bda4377c833b3499
    command: redis-server --save 20 1 --loglevel warning --requirepass $${REDIS_PASSWORD}
    env_file:
      - cache.env
    volumes:
      - /docker/cache/speedtest-tracker/redis:/data
    #    expose:
    #      - '6379'
    #    ports:
    #      - '6379:6379'
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf

  db:
    image: postgres:15@sha256:724292da1f2e50bdccfc3302ce75bbba7f4a6076701b588cc795fcac65683550
    env_file:
      - db.env
    volumes:
      - /docker/data/speedtest-tracker/postgres:/var/lib/postgresql/data
    networks:
      - default
      - backup-net
    #    ports:
    #      - "5434:5432"
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf

networks:
  backup-net:
    name: backup-net
    external: true
...
