---
services:
  speedtest-tracker:
    image: ghcr.io/linuxserver/speedtest-tracker:version-v1.14.8@sha256:4829a2ea61edd50370adc58050e6fbb93c96ed0c5d0215673b41df8347c9b2a2
    container_name: speedtest-tracker
    hostname: speedtest-tracker
    depends_on:
      - db
      - cache
    env_file:
      - speedtest-tracker.env
    volumes:
      - /docker/config/speedtest-tracker:/config
    ports:
      - "8765:80"
    healthcheck:
      test: curl -fSs http://localhost:80/api/healthcheck || exit 1
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 10s
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf

  cache:
    image: redis:8.10-alpine@sha256:becdda6c7f4b3fb42e42fd7f120bbf5c54c4caaaf16f26da24e4563d2c1f0576
    command: redis-server --save 20 1 --loglevel warning --requirepass $${REDIS_PASSWORD}
    env_file:
      - cache.env
    volumes:
      - /docker/cache/speedtest-tracker/redis:/data
    #    expose:
    #      - '6379'
    #    ports:
    #      - '6379:6379'
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf

  db:
    image: postgres:15@sha256:926f8799aef36e00001cfe15fba7abbd37d3c5224ea57e4c858e4bb670f10561
    env_file:
      - db.env
    volumes:
      - /docker/data/speedtest-tracker/postgres:/var/lib/postgresql/data
    networks:
      - default
      - backup-net
    #    ports:
    #      - "5434:5432"
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf

networks:
  backup-net:
    name: backup-net
    external: true
...
