---
services:
  prometheus:
    image: prom/prometheus:v3.11.3@sha256:e4254400b85610324913f0dc4acf92603d9984e7519414c5a12811aa6146acc3
    container_name: prometheus
    hostname: prometheus
    user: "1000:1000"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /docker/data/prometheus:/prometheus
    network_mode: bridge
    ports:
      - "9189:9090"
    restart: always
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf
...
