---
services:
  prometheus:
    image: prom/prometheus:v3.13.3@sha256:6976aa8a60fec930796ce5772b8d12da7a318a5daa8d40d69c5c7819a05eeed7
    container_name: prometheus
    hostname: prometheus
    user: "1000:1000"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /docker/data/prometheus:/prometheus
    network_mode: bridge
    ports:
      - "9189:9090"
    restart: always
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf
...
