---
services:
  prometheus:
    image: prom/prometheus:v3.14.0@sha256:5ce7540c3c00ef4ab0c9d2c995c6a5b9c421f44b4a115d97a2c7af3b1c21cbb0
    container_name: prometheus
    hostname: prometheus
    user: "1000:1000"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /docker/data/prometheus:/prometheus
    network_mode: bridge
    ports:
      - "9189:9090"
    restart: always
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf
...
