---
services:
  semaphore:
    image: semaphoreui/semaphore:v2.17.32@sha256:4db993aa2e50967b4e3e5df084a1e256e6d030291a209d7bb5cc9e86101dbf7b
    container_name: semaphore
    hostname: semaphore
    env_file:
      - semaphore.env
    ports:
      - "3001:3000"
    volumes:
      - /docker/config/semaphore:/etc/semaphore:rw
    depends_on:
      - postgres
      - tofu_backend
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf

  postgres:
    image: postgres:15@sha256:c635fa3e3b7421a659d34abdfd6d492f679cbe8149e261a501237b55c5a94212
    env_file:
      - db.env
    volumes:
      - /docker/data/semaphore:/var/lib/postgresql/data
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf

  tofu_backend:
    image: postgres:18@sha256:a9abf4275f9e99bff8e6aed712b3b7dfec9cac1341bba01c1ffdfce9ff9fc34a
    env_file:
      - tofu_backend.env
    volumes:
      - /docker/data/semaphore-tofu_backend:/var/lib/postgresql
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf
