---
services:
  semaphore:
    image: semaphoreui/semaphore:v2.18.4@sha256:e32c60f52e42799be077c6669f8dc9fcb6cedb1a1f851f791a6be851f4347c41
    container_name: semaphore
    hostname: semaphore
    env_file:
      - semaphore.env
    ports:
      - "3001:3000"
    volumes:
      - /docker/config/semaphore:/etc/semaphore:rw
    depends_on:
      - postgres
      - tofu_backend
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf

  postgres:
    image: postgres:15@sha256:1b92e7a80c021647bf70f5d3eb66066a998e4f5cf43c07bb9dc9f729782cf88e
    env_file:
      - db.env
    volumes:
      - /docker/data/semaphore:/var/lib/postgresql/data
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf

  tofu_backend:
    image: postgres:18@sha256:f7ce845ee6873dd84be93c9828fe0d1fab0f9707dc9ac569694657398b290bce
    env_file:
      - tofu_backend.env
    volumes:
      - /docker/data/semaphore-tofu_backend:/var/lib/postgresql
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf
