---
services:
  databasus:
    image: databasus/databasus:v3.32.1@sha256:12a7d5c04271216a3f11ad496021557b5d100177a243fb87b003cc014fe6bd7d
    container_name: databasus
    hostname: databasus
    volumes:
      - /docker/data/databasus:/databasus-data
    networks:
      - default
      - backup-net
    ports:
      - "4005:4005"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4005/api/v1/system/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf

networks:
  backup-net:
    name: backup-net
    external: true
...
