---
services:
  kometa:
    image: kometateam/kometa@sha256:570d3b64e08fbeda921d5a29b091092d03cb97f38b49b9f37fba3b76e5a24d26
    container_name: kometa
    hostname: kometa
    env_file:
      - kometa.env
    volumes:
      - /docker/config/kometa:/config
      #FIXME PWD is not compatible with Git Worktrees when updating the docker containers
      - "${PWD}/config/config.yml:/config/config.yml" #FIXME "PWD" might not work in all environments
    network_mode: bridge
    restart: no
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf
