---
services:
  kometa:
    image: kometateam/kometa@sha256:b265e952fcc3931ac378601faf9e6e0d90bee104fc70d9002f59c8678bf00b87
    container_name: kometa
    hostname: kometa
    env_file:
      - kometa.env
    volumes:
      - /docker/config/kometa:/config
      #FIXME PWD is not compatible with Git Worktrees when updating the docker containers
      - "${PWD}/config/config.yml:/config/config.yml" #FIXME "PWD" might not work in all environments
    network_mode: bridge
    restart: no
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf
