---
volumes:
  config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/docker/config/influxdb"
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/docker/data/influxdb"

services:
  influxdb:
    image: influxdb:2.9.1@sha256:cdd3dbdea45c2f43513abd06ee9644b6e05d2354a2b93ca829c9f07d716eaaac
    container_name: influxdb
    hostname: influxdb
    env_file: influxdb.env
    volumes:
      - config:/etc/influxdb2
      - data:/var/lib/influxdb2
    network_mode: bridge
    ports:
      - "8086:8086"
    restart: always
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf
