---
volumes:
  config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/docker/config/influxdb"
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/docker/data/influxdb"

services:
  influxdb:
    image: influxdb:2.9.1@sha256:f75e48af0598e8aec7986e991a848d19a119101a7d563a2e5db1dfaac9c45daa
    container_name: influxdb
    hostname: influxdb
    env_file: influxdb.env
    volumes:
      - config:/etc/influxdb2
      - data:/var/lib/influxdb2
    network_mode: bridge
    ports:
      - "8086:8086"
    restart: always
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf
