---
volumes:
  config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/docker/config/influxdb"
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/docker/data/influxdb"

services:
  influxdb:
    image: influxdb:2.9.1@sha256:003e028b675205f6148e5f30369fd3e854993b385f1e5e4d2d85bc9f8701bf28
    container_name: influxdb
    hostname: influxdb
    env_file: influxdb.env
    volumes:
      - config:/etc/influxdb2
      - data:/var/lib/influxdb2
    network_mode: bridge
    ports:
      - "8086:8086"
    restart: always
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf
