---
volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/docker/data/grafana"

services:
  grafana:
    image: grafana/grafana:13.0.1@sha256:0f86bada30d65ef9d0183b90c1e2682ac92d53d95da8bed322b984ea78a4a73a
    container_name: grafana
    hostname: grafana
    env_file: grafana.env
    volumes:
      - data:/var/lib/grafana
    network_mode: bridge
    ports:
      - "3000:3000"
    dns:
      - 192.168.6.4
      - 1.1.1.1
    restart: always
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf
