---
services:
  adguardhome-sync:
    image: ghcr.io/linuxserver/adguardhome-sync:version-v0.9.0@sha256:821d345f5d9fe9daf5912e28a50c87905a4c3530c163cad1773b078061f5da28
    container_name: adguardhome-sync
    hostname: adguardhome-sync
    env_file:
      - adguardhome-sync.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      #- CONFIGFILE=/config/adguardhome-sync.yaml #optional
    volumes:
      - /docker/config/adguardhome-sync:/config
    network_mode: bridge
    ports:
      - "8261:8080"
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf
