---
services:
  adguardhome-sync:
    image: ghcr.io/linuxserver/adguardhome-sync:version-v0.9.3@sha256:23314790177e4a1bea1109e915f0432ecb59b545e66edd49509240bfb69119f0
    container_name: adguardhome-sync
    hostname: adguardhome-sync
    env_file:
      - adguardhome-sync.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      #- CONFIGFILE=/config/adguardhome-sync.yaml #optional
    volumes:
      - /docker/config/adguardhome-sync:/config
    network_mode: bridge
    ports:
      - "8261:8080"
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf
