---
services:
  adguardhome-sync:
    image: ghcr.io/linuxserver/adguardhome-sync:version-v0.9.0@sha256:db6f5d9663d9700b102d7c31f246022cb4a2d4462cb9f360fa5b0f7b5f9165aa
    container_name: adguardhome-sync
    hostname: adguardhome-sync
    env_file:
      - adguardhome-sync.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      #- CONFIGFILE=/config/adguardhome-sync.yaml #optional
    volumes:
      - /docker/config/adguardhome-sync:/config
    network_mode: bridge
    ports:
      - "8261:8080"
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf
